# Generated by Django 3.1.7 on 2025-12-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('lottery_number', models.CharField(max_length=50)),
                ('ebarimt_picture', models.FileField(upload_to='ebarimt_pictures/')),
                ('aimag', models.CharField(max_length=50)),
                ('sum', models.CharField(max_length=50)),
                ('horoo', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Lottery',
                'verbose_name_plural': 'Lotteries',
                'db_table': 'lottery_table',
            },
        ),
    ]
